// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationSubscriptionController from "./application_subscription_controller"
application.register("application-subscription", ApplicationSubscriptionController)

import FilterSearchController from "./filter_search_controller"
application.register("filter-search", FilterSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
